### ISSUE TITLE
1440p, 4K videos do not load at all

### ISSUE THREAD

**Issue by that404nerd** [futo-org/grayjay-android#1278]
### What happened?

As the title mentions, 1440p and 4k videos don't load at all. I tried to switch from 1080p to 1440p but the video doesn't load at all. Like the video doesn't show buffering or anything. Only the pause button which on clicking doesn't do anything. I reinstalled the app but nothing changed.

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

193

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by BenDundon** [comment]
Seconding this, I'm unable to cast media at any size over 1080p (at least from Youtube, I don't have any other sources with that size to check others)

**Comment by dgb-2000** [comment]
Same issue for me. Incidentally, the resolutions greater than 1080p are listed with "video/webm", whereas 1080p and below are listed as "video/mp4". Not sure if this is a coincidence, or actually related to the problem..

**Comment by dgb-2000** [comment]
Correction on my part: The issue only happens for me, when trying to cast to my PC using FCast. Watching a 4K Video directly on my phone works (though my screen resolution limits the usefullness..).

**Comment by support-grayjay** [comment]
@that404nerd this should be fixed in the latest version of Grayjay (v264) and latest version of Youtube plugin (209). Please retest and provide us with feedback.

@dgb-2000 & @BenDundon your issue appears to be different and related to casting. Could you please open a new issue for this?

**Comment by that404nerd** [comment]
> @that404nerd this should be fixed in the latest version of Grayjay (v264) and latest version of Youtube plugin (209). Please retest and provide us with feedback.
> 
> @dgb-2000 & @BenDundon your issue appears to be different and related to casting. Could you please open a new issue for this?

Still doesn't work for me. Anything higher than 1080p doesn't work at all.

**Comment by support-grayjay** [comment]
Could you please provide a bit more information about the device you are using?

**Comment by that404nerd** [comment]
> Could you please provide a bit more information about the device you are using?

Device model: Lenovo Tab M10
CPU: Qualcomm Snapdragon 695

**Comment by that404nerd** [comment]
@support-grayjay Still not working for me. Any idea on this one?

**Comment by DutchFlander** [comment]
Samsung Galaxy A53 user here and the issue is present. 
Interestingly on OnePlus 7T pro and Samsung S22 with the same settings the issue is not present.
So I assume, we have some device related issues. Codecs maybe?

**Comment by DutchFlander** [comment]
Samsung Galaxy A53 user here and the issue is present. 
Interestingly on OnePlus 7T pro and Samsung S22 with the same settings the issue is not present.
So I assume, we have some device related issues. Codecs maybe?

**Comment by Zvonimir-FUTO** [comment]
Can you try with the latest Grayjay update? There have been some fixes with UMP implemented.

**Comment by MrTheXade** [comment]
Even with the latest update it still doesn't work, even when loading an UMP source. Galaxy Tab a9+

Only 1440p and 4k don't work, the other resolutions work fine as they always did

**Comment by Zvonimir-FUTO** [comment]
Thank you for feedback. Will have to continue investigating this issue.

**Comment by Zvonimir-FUTO** [comment]
This should be now fixed with latest version of Grayjay and Youtube. If not please provide video examples so we can look further into it.

**Comment by DutchFlander** [comment]
> This should be now fixed with latest version of Grayjay and Youtube. If not please provide video examples so we can look further into it.

Version:
![Image](https://github.com/user-attachments/assets/d3bcfd06-5338-41cd-aeec-13762e8413e4)

Video:
https://github.com/user-attachments/assets/ec28ffec-73d8-4630-81a0-bd8512c5c5b0

Used link:
https://www.youtube.com/watch?v=LXb3EKWsInQ

My mobile has 2K display

**Comment by that404nerd** [comment]
Yep still the same issue. A black screen.

**Comment by that404nerd** [comment]
> This should be now fixed with latest version of Grayjay and Youtube. If not please provide video examples so we can look further into it.

Also what's the reason for this issue? The desktop version works just fine. Is it the codecs or something like that?

**Comment by Zvonimir-FUTO** [comment]
> Also what's the reason for this issue? The desktop version works just fine. Is it the codecs or something like that?

mp4 containers didn't work with UMP streams which was fixed in the mentioned update. However, that doesn't seem to be the root of your issue. Would be easier to fix it if we could reproduce it.

Recently Youtube messed UMP streams again so we fixed iOS streams in v229. While we are working on fixing UMP, could you try and test 2k/4k resolutions on iOS streams?

**Comment by that404nerd** [comment]
> > Also what's the reason for this issue? The desktop version works just fine. Is it the codecs or something like that?
> 
> mp4 containers didn't work with UMP streams which was fixed in the mentioned update. However, that doesn't seem to be the root of your issue. Would be easier to fix it if we could reproduce it.
> 
> Recently Youtube messed UMP streams again so we fixed iOS streams in v229. While we are working on fixing UMP, could you try and test 2k/4k resolutions on iOS streams?

I will try and update you about it

**Comment by that404nerd** [comment]
> > Also what's the reason for this issue? The desktop version works just fine. Is it the codecs or something like that?
> 
> mp4 containers didn't work with UMP streams which was fixed in the mentioned update. However, that doesn't seem to be the root of your issue. Would be easier to fix it if we could reproduce it.
> 
> Recently Youtube messed UMP streams again so we fixed iOS streams in v229. While we are working on fixing UMP, could you try and test 2k/4k resolutions on iOS streams?

Huh. The streams are all shown as IOS streams. Still doesn't work with the new plugin update. v231 to be exact. 

Edit: Force Experimental UMP streams is disabled. Just edited the comment to let you know. Please look into this. Thanks.

**Comment by that404nerd** [comment]
Alright it looks like 1440p, 4k are working on my device. But changing the quality makes the app unresponsive. Please fix this. Thanks!

**Comment by DutchFlander** [comment]
Version Code: 284
Version Name: 284
Version Type: release

Youtube plugin version: 235

The issue is still present. Only 1080 is playing :(

**Comment by Zvonimir-FUTO** [comment]
> Version Code: 284 Version Name: 284 Version Type: release
> 
> Youtube plugin version: 235
> 
> The issue is still present. Only 1080 is playing :(

Could you check if that is an issue on both iOS streams and UMP?

When you play a video, when choosing quality you will see a text indicating if you are playing iOS stream or UMP stream. By default it should be iOS stream unless it fails it should fallback to UMP. However, you can force UMP stream in Youtube plugin settings by enabling "Force Experimental UMP streams".

**Comment by DutchFlander** [comment]
Do you have a link for a video that can support UMP?
All I can see so far is iOS stream in my list:

![Image](https://github.com/user-attachments/assets/2df75c8a-4541-4fd1-809d-d06c1727cfed)

Only 1080 mp4 or webm is playing.

**Comment by Zvonimir-FUTO** [comment]
>When you play a video, when choosing quality you will see a text indicating if you are playing iOS stream or UMP stream. By default it should be iOS stream unless it fails it should fallback to UMP. **However, you can force UMP stream in Youtube plugin settings by enabling "Force Experimental UMP streams".**

Please try the bolded part.

**Comment by DutchFlander** [comment]
Sorry, I was not reading it carefully:

![Image](https://github.com/user-attachments/assets/55fe0f8f-afc0-4e67-a27e-294b89beabbf)

Only 1080 is functioning here as well :(

**Comment by Zvonimir-FUTO** [comment]
Which device are you using?

**Comment by DutchFlander** [comment]
> Samsung Galaxy A53 user here and the issue is present. Interestingly on OnePlus 7T pro and Samsung S22 with the same settings the issue is not present. So I assume, we have some device related issues. Codecs maybe?

My device has 2K screen.

**Comment by that404nerd** [comment]
Reopening this issue. 1440p, 4k still doesn't work. I tried enabling force ump streams but it still doesn't work. 

Android version - 14
Device - Lenovo Tab M10

**Comment by DutchFlander** [comment]
Hi,

Yesterday I received Android 16 update for my Samsung Galaxy A53 and since then 4K video is working.
I'm not limited to 1080p videos only anymore, so I guess some missing codecs were added to Android 16 (maybe?).

Hopefully such info can help the developers to fix it for older androids.

KR,
DF

**Comment by Zvonimir-FUTO** [comment]
Adding link for easier reproduction: https://www.youtube.com/watch?v=i63u-iAnhuk

**Comment by Zvonimir-FUTO** [comment]
This should be resolved in v297
