### ISSUE TITLE
[Bug] Synchronize Watch Later between Devices

### ISSUE THREAD

**Issue by SCBionicle** [futo-org/grayjay-android#1630]
### Use Cases

There's a lot of videos that I end up wanting to watch and I find it really handy to bookmark the videos in the watch later playlist, especially since the watch later playlist automatically clears when you watch the video.

### Proposal

I will switch between my desktop and phone to watch videos. Since the desktop just released into open alpha, it would be very handy to the synchronization feature synchronize the watch later list between devices.

**Comment by Zvonimir-FUTO** [comment]
Hey Seth, that should already be synced but the view doesn't refresh immediately.  Can you try opening different tabs or closing and opening the app to see if the change was made?

**Comment by SCBionicle** [comment]
I'll take another look when I get home from work, and I'll post an update.

**Comment by SCBionicle** [comment]
So, it does sync somewhat. It goes back and forth with adding to the watch later list on desktop, only if I have already created a watch later list on desktop.

It does not, however, download my already existing items in my watch later list from my phone to my desktop prior to me creating a watch later list on the desktop.

This may be a bug.

**Comment by SCBionicle** [comment]
It would be difficult to test if the sync will retroactively add and remove items from a playlist after the devices reconnect from being disconnected.

**Comment by Paeniche** [comment]
I've had intermittent success with "watch later" syncing. Watch later occasionally syncs, but when it stops syncing I consistently see this error when opening Grayjay on my phone. Terminal log is from my desktop (Fedora 41, Plasma) and I removed the session id and public key.


```SyncSocketSession:PerformVersionCheck 2
HandshakeAsResponder: Read message size 96
HandshakeAsResponder: Wrote message size 48
T:Handshake complete with (LocalPublicKey = , RemotePublicKey = )
T:Sent AUTHORIZED with session id 
T:onAuthorized (isNewlyAuthorized = False, isNewSession = True)
T:public key authorized
StateSync:New session 
Failed to run as responder: System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
 ---> System.Net.Sockets.SocketException (32): Broken pipe
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Grayjay.ClientServer.Sync.Internal.SyncSocketSession.Send(Byte opcode, Byte subOpcode, ReadOnlySpan`1 data)
   at Grayjay.ClientServer.Sync.Internal.SyncSession.Send(Byte opcode, Byte subOpcode, Byte[] data)
   at Grayjay.ClientServer.Sync.Internal.SyncSession.SendJsonData(Byte subOpcode, Object data)
   at Grayjay.ClientServer.States.StateSync.CheckForSync(SyncSession session)
   at Grayjay.ClientServer.States.StateSync.<>c__DisplayClass36_1.<CreateSocketSession>b__3(SyncSession sess, Boolean isNewlyAuthorized, Boolean isNewSession)
   at Grayjay.ClientServer.Sync.Internal.SyncSession.CheckAuthorized()
   at Grayjay.ClientServer.Sync.Internal.SyncSession.Authorize(SyncSocketSession socketSession)
   at Grayjay.ClientServer.States.StateSync.<>c__DisplayClass36_0.<CreateSocketSession>b__1(SyncSocketSession s)
   at Grayjay.ClientServer.Sync.Internal.SyncSocketSession.<StartAsResponder>b__34_0()
Session closed

**Comment by SCBionicle** [comment]
Hmm? What's this?

![image](https://github.com/user-attachments/assets/bf351c91-576c-462b-a1ba-d2c595814a34)

Why am I being billed with this?

**Comment by SCBionicle** [comment]
Btw, observed behavior is that new (not existing) entries sync fine to desktop if the devices are actively connected, but do not retroactively update if the changes were when they were disconnected.

**Comment by Zvonimir-FUTO** [comment]
> Hmm? What's this?
> 
> Why am I being billed with this?

You are not being billed for this but for a weird reason you got emailed for triggering the job for a labeler and we ran out of the worker minutes. Anyway, we removed it since it not that useful and we don't you getting those kind of emails. :)

**Comment by SCBionicle** [comment]
Update on observed behavior: any changes made on the android version of watch later is not pushed to desktop retroactively, so when desktop syncs after reconnection to android, it readds the desktop watch later list to the android device.

This behavior does not happen on any other playlist, just watch later. I'm going to open GrayJay desktop and link to this issue because this issue is related to both apps.

**Comment by SCBionicle** [comment]
I am wondering if there had been any updates with this issue.

**Comment by Zvonimir-FUTO** [comment]
We are working on improvements for Sync but there are also some more urgent issues we have to deal with first as well.
Once this issues has been solved we will comment here and of course once it has been released this issue will be closed so if anything new pops up it will be reflected here.

**Comment by Zvonimir-FUTO** [comment]
Fixed in latest versions of both android v285 and desktop v5.

**Comment by SCBionicle** [comment]
How do I get my 42 video watch later list to upload to my PC after this update?

**Comment by SCBionicle** [comment]
Is this fixed?

It looks to be partially fixed. New items that were added on the phone app since the update successfully pushes to the desktop, but things that were on there since before the update didn't get pushed to the desktop. 

Should this issue be reopened?

**Comment by Zvonimir-FUTO** [comment]
> Is this fixed?
> 
> It looks to be partially fixed. New items that were added on the phone app since the update successfully pushes to the desktop, but things that were on there since before the update didn't get pushed to the desktop.
> 
> Should this issue be reopened?

Hmmm... thought we fixed it. Could you try resyncing your devices? Remove sync and then add again.

**Comment by SCBionicle** [comment]
Just did. It does not appear that changes to watch later on the phone isn't retroactively synced to desktop upon connection. This issue appears exclusive to the watch later list and other playlists work just fine.

**Comment by SCBionicle** [comment]
Desktop Version: 5
Android App version: 285

**Comment by SCBionicle** [comment]
Android logs: `75a56298-d803-4ba8-a563-b8808eaddaab`
Desktop logs: [log.txt](https://github.com/user-attachments/files/19037091/log.txt)

**Comment by NTpspE** [comment]
I've noticed if I add things to my watch later on my phone, then open the app on any other device (tablet / PC) then the watch later on that device is empty. 

If it's open on both devices however, things added do appear on both devices. 

One workaround has been to go into each video and re-add it to watch later again (which does nothing on the source device, but does cause it to then appear on the other device) - though it's a little annoying opening and closing each video to perform this. 

Perhaps on the watch later screen there could be a 'sync watch later' button that performs this? Just tries to re-add everything in the watch later list to it again?

**Comment by SCBionicle** [comment]
> I've noticed if I add things to my watch later on my phone, then open the app on any other device (tablet / PC) then the watch later on that device is empty.
> 
> If it's open on both devices however, things added do appear on both devices.
> 
> One workaround has been to go into each video and re-add it to watch later again (which does nothing on the source device, but does cause it to then appear on the other device) - though it's a little annoying opening and closing each video to perform this.
> 
> Perhaps on the watch later screen there could be a 'sync watch later' button that performs this? Just tries to re-add everything in the watch later list to it again?

This is the same behavior I have observed. Except, anything in the desktop watch later will be forced onto my phone every time the two devices connect.

**Comment by NTpspE** [comment]
> This is the same behavior I have observed. Except, anything in the desktop watch later will be forced onto my phone every time the two devices connect.

Yes exactly the same here actually, I recently reconnected my phone to the PC and there was a *very* persistent video that kept being added to the 'watch later' list on my phone. 

Last time I used it I did remove that particular video from the 'watch later' on the PC, and it doesn't appear to have come back - but it does feel like PC->Mobile was working correctly, whereas Mobile->PC is not (not retroactively adding them).

**Comment by Zvonimir-FUTO** [comment]
Fixed in v293.

**Comment by SCBionicle** [comment]
This bug is partially fixed. The watch later list will retroactively add the videos to the list onto the PC from the phone, but will not retroactively remove videos on PC that had been removed on the phone. Instead, the PC will readd the videos on the phone.

It might be worth reopenning this issue.

(I wrote this after a long work day, if what I wrote is confusing [which it's bound to be], I'd be happy to reexplain.)

**Comment by Zvonimir-FUTO** [comment]
Should be fixed in latest version of both desktop (v6) and android (v298).

**Comment by SCBionicle** [comment]
Not fixed. New behavior: when disconnected from both relay and direct sync, if you remove a video from the desktop's watch later list and reconnect the phone, the phone will readd the video to the watch later list.

Steps to reproduce:
1. Force close the android app
2. Remove video from watch later on desktop
3. relaunch GrayJay on Android
4. observe removed video become readded onto watch later list on desktop

It may be worth reopening this issue.

**Comment by SCBionicle** [comment]
I will say, removing a video from the phone's watch later list and seeing that removal show up on desktop is a major improvement. It seems most use cases seem to be fixed when I tested this, but at least this edge case (https://github.com/futo-org/grayjay-android/issues/1630#issuecomment-2849035274) appears to be left over. It might be worth double checking with the community, but this may not be as high priority anymore.

**Comment by Zvonimir-FUTO** [comment]
Thank you for reporting it. It's reproducible so shouldn't be too hard to fix.

**Comment by SCBionicle** [comment]
Not fixed. The issue is now reversed. Videos now readd on the phone app.

**Comment by SCBionicle** [comment]
Sorry, I had very little time to try out the new update.

**Comment by Zvonimir-FUTO** [comment]
No need to apologize, you help us a lot actually. 

Is this with the latest android version as well? v306
I wasn't reproduce this.

**Comment by SCBionicle** [comment]
Yes, it's on the latest. When I go through reproducing testing steps it doesn't happen. However, in the wild, it happens frequently.

On of the trouble shooting steps is that installed a clean installation of the desktop version and synced it from my phone. But, no luck.

**Comment by SCBionicle** [comment]
When I get the time, I can try to do the testing steps I usually do.

**Comment by SCBionicle** [comment]
Ok, some information they may be helpful. This issue only seems to appear when there is a bunch of watch history to synchronize. If I try manually induce a sync without adding to the watch history, the issue does not manifest.

There may be a sort of race condition between syncing the watch history and the watch later lists.

**Comment by SCBionicle** [comment]
Every time the issue had manifest, (I barely watch on my PC) I have watch videos both on my watch later list and from the home page. Often times that I actually sync, there are probably 30 entries of history being uploaded to the PC and about 5-10 watch later videos removed from the list. Most, if not all, the videos that were removed from watch later (it's hard to verify if it's all of the videos) were readded upon the sync when this issue manifests.

The only thing about this bug is that it breaks on the quantity of the sync.

**Comment by SCBionicle** [comment]
Sorry for the late reply.

So, with the option auto-remove items from watch later enabled (also, in my environment, downloads on watch later is enabled on phone, not desktop):
1. make sure the watch later and watch history on Desktop and phone are synchronized
2. Disconnect the connection between desktop and phone (I often have the desktop application closed)
3. Watch an item on phone until playback crosses the auto-remove threshold or to the end (you may have to repeat this several times for the issue to crop up)
4. Reconnect sync between desktop and phone
5. Observe none, some, or all of the videos that were watched be re-added on the phone's watch later. Also, observe that the videos that were not re-added to the phone is removed from the desktop watch later

This issue may be to a race condition in the code and is reproducible both with and without the relay. This issue often does not crop up on just one video, so you may have to repeat step 3 multiple times for the issue to reappear.

Also, in my testing environment, I have over 70 videos in the watch later list and over 200 videos in the watch history. So, this issue may not appear on clean installations, but in installations with large amounts of data.
