### ISSUE TITLE
When downloading  some videos  on BiliBili the download fails 

### ISSUE THREAD

**Issue by Starduck536** [futo-org/grayjay-android#1707]
What happened?
When downloading  some videos  on BiliBili the download fails  "Failed to download Source Web 403 error"
 im downloading audio only  examples
https://www.bilibili.com/video/BV1KW411r75M https://www.bilibili.com/video/BV1vs411p7Cp 
 

Grayjay Version

278

What plugins are you seeing the problem on?

BiliBili (CN)

Plugin Version

20

When do you experience the issue?

  While logged out

Relevant log output
Failed to download Source Web 403 error

**Comment by kaidelorenzo** [comment]
should be addressed by these changes

https://gitlab.futo.org/videostreaming/grayjay/-/merge_requests/141

**Comment by Starduck536** [comment]
I'm still getting the web 403 error on BiliBili videos/audio downloads

**Comment by Zvonimir-FUTO** [comment]
> I'm still getting the web 403 error on BiliBili videos/audio downloads

As you can see the PR was not merged and issue hasn't been closed yet.

**Comment by Starduck536** [comment]
My bad sorry about that. 

> As you can see the PR was not merged and issue hasn't been closed yet.
