### ISSUE TITLE
Youtube playback stops when switching network/wifi

### ISSUE THREAD

**Issue by Kelvin-FUTO** [futo-org/grayjay-android#1854]
### What happened?

Switching to a different ip/network/wifi may cause playback on UMP to stop working.
This is due to the IP-bound nature of UMP, and this needs to be handled by the app properly.

### Grayjay Version

281

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

224

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [x] N/A

### Are you using a VPN?

No

### Relevant log output

```shell

```

**Comment by Stormhammer1399** [comment]
I also experience this issue. Anytime I switch networks, be it turning my VPN on or off or going from cellular to wireless, the video freezes. I have to close the app entirely to get it to let me play the video again.

**Comment by Kelvin-FUTO** [comment]
> I also experience this issue. Anytime I switch networks, be it turning my VPN on or off or going from cellular to wireless, the video freezes. I have to close the app entirely to get it to let me play the video again.

We have some work in progress fixes. We are aware why its happening, just have to handle more edge cases related to it.

**Comment by mohag** [comment]
On an older version, the video restarted on changing networks and seeking stopped working (I think with the IOS fallback toast) (I mostly switch to the YT app in those cases - I have premium and it allows continuing there I was... (It was mostly when listening to videos on my way to work, when I left the range of my WiFi)

**Comment by RZ22F** [comment]
@Zvonimir-FUTO so someone mentioned Grayjay having a memory leak with UMP, well Grayjay uses 1GB while actively playing youtube video.
Up from... I recon 300-400 MB.

**Comment by Kelvin-FUTO** [comment]
A fix was deployed for switching network. (v226)
Its not an ideal fix, but at least it keeps playback going.

**Comment by RZ22F** [comment]
So, Mobile Data still doesn't work for Youtube video playback on Grayjay.
I reinstalled the app, i reinstalled Google Play Services thinking that might somehow help, i cleared the cache from every single app that HAD cache manually (about 100 of them, system apps and plugins and stubs or whatever they're called, included) and the thing still doesn't play back any video. Proof in screenshots.

![Image](https://github.com/user-attachments/assets/30a91d46-a4dc-4365-a30e-af73f64c2293)
![Image](https://github.com/user-attachments/assets/04fa59a0-90f6-4986-a3ac-6f955e2b5485)
![Image](https://github.com/user-attachments/assets/c6533c3e-5087-4007-b685-ad48687f3ec8)

@Kelvin-FUTO

**Comment by RZ22F** [comment]
To add, no switch was done.
Just straight up cleared EVERYTHING, restarted the phone, turn on mobile data, and...attempt playback.

**Comment by Zvonimir-FUTO** [comment]
@RZ22F if I understand it correctly, you don't can't play anything over mobile data? This issue is related to interruption on switching networks but yours appears to be unrelated. Could you please open another issue for your case?

**Comment by RZ22F** [comment]
Done.
