### ISSUE TITLE
System brightness is not restored with overlay playback

### ISSUE THREAD

**Issue by aand18** [futo-org/grayjay-android#2055]
### What happened?

1. Activate "control system brightness" in settings 
2. Play video fullscreen
3. Adjust brightness 
4. Switch app - Grayjay should pass to overlay (pop-over) playback
5. System brightness is not restored.

Bonus issue:
6. Exit pop-over. System brightness is not restored. 

Android: 14
One UI:  6.1.1

### Grayjay Version

285

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [x] N/A

### Are you using a VPN?

No

### Relevant log output

```shell

```

**Comment by aand18** [comment]
Suggestion:
Probably the way brightness is adjusted currently is not the way. 
E.g. NewPipe adjusts brightness when full-screen, but does not appear to mess with system brightness ("Adaptive Brightness" system setting stays On, system brightness setting stays unchanged, and yet fullscreen video can go up to max screen brightness).

E.g. NewPipe full screen brightness goes to  max screen brightness:
![Image](https://github.com/user-attachments/assets/5d15fdd8-77a7-4516-91cf-20fe82e10417)

While system brightness stays unchanged:
![Image](https://github.com/user-attachments/assets/94dd70b0-0754-4fad-962a-d82c4d6b46d3)

**Comment by shadow-identity** [comment]
This could be expected, as user is still watching the video, but if they close the overlay, the adaptive brightness should be restored, but it is not.

Also, if the user is watching a video with alternated brightness, and then closes the app (by swiping it up), the adaptive brightness is also not restored.

**Comment by aand18** [comment]
> This could be expected, as user is still watching the video, but if they close the overlay, the adaptive brightness should be restored, but it is not.
IMO it's jarring and bad UX to disable adaptive brightness when switching to a different app.  
I often found myself outside in the sun with %5 brightness and can't see anything on the screen, not even to adjust the brightness (!) because of Grayjay. 

> Also, if the user is watching a video with alternated brightness, and then closes the app (by swiping it up), the adaptive brightness is also not restored.
Like I've said, there is a way to not alter system settings, Newpipe is using it.

**Comment by kaidelorenzo** [comment]
Should be addressed by these changes

https://gitlab.futo.org/videostreaming/grayjay/-/merge_requests/99

**Comment by Zvonimir-FUTO** [comment]
Fixed in v312.

**Comment by shadow-identity** [comment]
Still reproducible (the system brightness is not restored) when swiping up the Grayjay from the app switcher (aka overview aka recents)

**Comment by shadow-identity** [comment]
May the window attribute screenBrightness work in Grayjay case? As @aand18 said, it does not require any code to restore the system brightness because it does not alternate the system brightness.
```kotlin
fun Activity.setWindowBrightness(brightnessFraction: Float) {
    val clamped = brightnessFraction.coerceIn(0.0f, 1.0f)
    window.attributes = window.attributes.apply {
        screenBrightness = clamped
    }
}
```

**Comment by Zvonimir-FUTO** [comment]
I wasn't able to reproduce this, could you please confirm that you have "Restore system brightness" enabled in the settings?

If not could you also give information the device you using? Which model and what android version.

**Comment by kaidelorenzo** [comment]
Yeah @shadow-identity we'll look into that

**Comment by shadow-identity** [comment]
I made a short video: https://drive.google.com/file/d/1qzXnwsgkGtMwtPNop9QqLVc6jZhppA8O/view?usp=sharing
I'm on v 316, Android 15

**Comment by kaidelorenzo** [comment]
Should be addressed by these changes https://gitlab.futo.org/videostreaming/grayjay/-/merge_requests/124

**Comment by rmsa5** [comment]
issue still there in grayjay 327, on android 16 (GrapheneOS).

Grayjay is the only app I have that messes with system brightness settings (especially by tempering with "adaptative brighness") while all other similar apps (VLC, just player, youtube revanced...) that have fullscreen brightness control seem to do it in a way that only overrides brightness when app is in scope, and don't touch system brightness setting _at all_

One way of revealing that grayjay still messes with system brightness settings (but probably tries to recover them on exit) is if playing back a video in grayjay in fullscreen, changing brightness from grayjay, and then killing grayjay app. System "adaptative brightness" setting is _again_ disabled whereas it was enabled before using grayjay.

Please fix the way you handle brightness 🙏

**Comment by shadow-identity** [comment]
Sure, because the pull request that was mentioned above is still not merged (tho it is approved).

**Comment by Zvonimir-FUTO** [comment]
Fix added to master, will be included in next version.

**Comment by aand18** [comment]
@Zvonimir-FUTO great news! How can I tell when it's published, so I can test? I have automatic updates (obtainium) and not sure if the APK it's pulling is 'release' or just some daily build.

**Comment by Zvonimir-FUTO** [comment]
> [@Zvonimir-FUTO](https://github.com/Zvonimir-FUTO) great news! How can I tell when it's published, so I can test? I have automatic updates (obtainium) and not sure if the APK it's pulling is 'release' or just some daily build.

Issue will be either closed or comment will be added once it has been released.

**Comment by Zvonimir-FUTO** [comment]
New stable released, should be fixed now.

**Comment by chris246** [comment]
Hi
I still have the issue that Grayjay disables automatic brightness adjustment and does not re-enable it.

Device is Pixel 7 Pro with Android 16 and Grayjay installed via apk

**Comment by Zvonimir-FUTO** [comment]
@chris246 could you please open a new bug report for this instead of necro bumping?
