### ISSUE TITLE
Subtitles do not work

### ISSUE THREAD

**Issue by GenericUsernameIsNotAvailable** [futo-org/grayjay-android#2216]
### What happened?

When selecting subtitles while watching a video, they do not then show up on screen. This has happened on the latest version and on the one previous but it has bot always been the case.
Also, cheeky feature request to have an option to always show subtitles when available (not auto-generated, or yes also when auto-generated)

### Grayjay Version

306

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

248

### When do you experience the issue?

- [x] While logged in
- [ ] While logged out
- [ ] N/A

### Are you using a VPN?

No

### Relevant log output

```shell

```

**Comment by Zvonimir-FUTO** [comment]
Wasn't able to reproduce it. Does it happen for both auto-generated and added subtitles? Does it happen on every Youtube video?

**Comment by GenericUsernameIsNotAvailable** [comment]
I've attemtped to reproduce it. And I also am unable to.

However, i can confirm at the time it effected both auto and added subtitles on multiple videos across the youtube plugin.

I'll mark the issue as resolved... but if it comes up again in the future, I'll make note of it again.

**Comment by sychare** [comment]
This is happening very frequently for me, but not always. Isn't just auto-generated subtitles either, seems to fail for both types.

If it's of any diagnostic value when it fails it is obvious as the video does not pause whilst enabling in the way it would if it were to enable subtitles correctly.

**Comment by Zvonimir-FUTO** [comment]
Reopening issue for now but it's gonna be hard to fix it without any reproduction steps. If you could find any connection to it, like it happening for specific type of video or from specific creator or language or something please share that with us.

**Comment by sychare** [comment]
Been playing around with this looking for any commonalities to narrow it down.

Steps
1. Open https://www.youtube.com/watch?v=oI5z8E8mbOw
2. Enable subtitles

If that works, force stop Grayjay, try again. It is that simple. Sometimes it works and sometimes it doesn't, for the same video. Failure is random, almost feels like a race condition somewhere.

**Comment by Zvonimir-FUTO** [comment]
Been testing this for a while on 2 devices but couldn't reproduce it. Will see if someone else can reproduce it.

**Comment by GenericUsernameIsNotAvailable** [comment]
Right, I've got it again now. Just by chance annoyingly. Ive tested three videos, all unable to produce subtitles.
As @sychare said, the video doesn't pause/reload quickly when trying to enable it (ad it normally would when subtitles work) however, it does pause/reload when disabling them again - despite subtitles not being displayed.

My phone is on 17% battery but not on any sort of power saving mode. No other apps are open. However, Samsung Smartthings was running in background and trying to refresh location.
The time is after midnight (mentioning this in case subscriptions were trying to load or something).

Wifi is stable.
I tried enabling subtitles just a few seconds or less as soon as the video loaded. And I'm pretty sure I did it in portrait (without have the video full screen).
I would suggest it could be a scaling/ proportion issue, but the fact it doesn't buffer or anything when initially enabling it suggests it might be something more.

**Comment by GenericUsernameIsNotAvailable** [comment]
When going back into the app now, i tried to exit settings, but instead it closed the app. I reopened it, and tried doing the subtitles again, and now it works.

Perhaps its something to do with the intialisation when opening the app? Maybe it skips a process?

**Comment by kaidelorenzo** [comment]
Spotify does for most songs but you do need a free account. 

Bilibili also has lots of subtitles but they only show up if you log in again a free acount

would either of those work for you

**Comment by sychare** [comment]
Thanks. Just given Spotify a try and subtitles appear to be fine... however I now can't get them to fail for YouTube either. Urgh. I'll try again later!

**Comment by PlatonicSalad** [comment]
I'm having the same issue, there's no buffer and subtitles don't load. Also, videos won't download if subtitles are selected. However, they will download if subtitles are not selected. I just started having this issue after using loginfallback, so it might be related to that.

**Comment by Giesa-lab** [comment]
I'm seeing this with GrayJay v306 and YouTube plug-in v251 ... I can't remember when I confirmed it as working, but a few months ago was the last time I needed that... maybe plug-in 23? ... the mid thirties perhaps, not only auto but parsed all the manually inserted options that are available at YouTube's API, and website. 

See attached screenshots of this video to reproduce. 

700 Marines mobilized to Los Angeles - ABC News 
https://www.youtube.com/watch?v=JNqhtlHeQd0 

GrayJay - 
![Image](https://github.com/user-attachments/assets/e41228b9-d3dc-4262-97f6-28a89fd0d017)

YouTube in Chrome Browser - 
![Image](https://github.com/user-attachments/assets/cff691c4-aba5-4931-87b9-4b8505ae0153)

Of course YouTube is using Google subtitling with auto-generated translation on many videos.
I don't know how the plug-in pulls this info from YouTube, maybe something changed in their API ?

💡 idea 💡 
What would be really sweet, would be to integrate an open source realtime auto multi-lingual daemon.
Then auto subtitles could work on every platform, not just Youtube, but Rumble and Odysee etc. too !

**Comment by MRDGH2821** [comment]
I found temporary workarounds for those stumbling here:

Linux - https://flathub.org/apps/net.sapples.LiveCaptions (English only as of now)
Android - https://www.makeuseof.com/how-to-turn-on-and-use-live-caption-on-android/ (Download languages as needed)

----

On that note, I read someone suggesting to generate captions on device itself, that would be cool to have if subtitles from source (youtube, etc) don't work

**Comment by VKen** [comment]
Hi, I've been experiencing this the past few weeks. Hope to contribute here to debugging.
I can only describe my experience for youtube plugin's performance, as it's the one i use most.

First, I'm in a country with DNS poisoning and DNS transparent proxying (Fake cloudflareDNS, Fake googleDNS). The DNS performance speed here is abysmal, unless I VPN.

I've tried different permutation of steps across versions:
- Grajay version 318-321
- Youtube plugin maybe 249-251 

Some workaround works earlier, then in later date or later version it stopped working.

Some settings i tested with:
- force UMP redirect set to true (earlier date/versions) 
- force UMP redirect set to false (current latest versions, can't get captions/subtitles to work)

I'm going to describe what steps I took and what I see:
1. select a youtube video from subscriptions
2. video page interface loads component by component starting with some attempt to load video, but video loading spinner continues
3. video page interface loads comments with spinner, video loading spinner continues
4. comments loaded and displayed, then video loading spinner flickers and video starts loading
5. video starts playing.

On an expected normal behavior:
6. click to open video options, and select a language subtitles
7. video flickers/flashes black to load subtitle
8. video returns and subtitles shows.

On the case of somewhat working behavior:
6. click to open video options, and select a language subtitles
7. video continues playing without stopping for more than 5 seconds, sometimes 30 seconds, then it does the flicker and loading
8. video returns and subtitles shows.

Failure behavior:
- subtitles selected, video didn't flash to reload, even after waiting.
- at this point, with a subtitle language already selected, unselection of subtitle causes video to flicker/flash to reload.
- re-selecting the unselected subtitle language, the video still doesn't flicker to show signs of loading.

On workarounds when the subtitle doesn't work, doesn't reach step 8
Option 1: play from history (sometimes works)
8. stop video and close video interface, and also close minified pip interface 
9. enter grayjay history tab
10. select youtube video to replay
11. video interface loads and plays at recorded timestamp
12. click to open video options, and select a language subtitles
13. video continues playing without stopping for more than 5 seconds, sometimes 30 seconds, then it does the flicker and loading
14. video returns and subtitles shows.

Option 2: use a VPN, as there seems to be some ip restriction (ump failed to load) and sometimes it is due to IP with bad repute
8. stop video
9. connect vpn
10. retry with newly start video and select subtitle to watch it load instantly or wait 15 to 30 seconds to see delayed response.
11. if it doesn't work stop video, try the history tab video entry point
12. if it doesn't work cycle VPN region, retry again

Latest extensive test with grayjay 320 and youtube 251, I've not had any success with the subtitles. Both with UMP and iOS fallback video, all doesn't work.
Now I just got grayjay 321 and youtube plugin 251, still nothing works.

I do see the cipher/bot-guard token toast message 2-3 times (i think). The first one is too quick when loading and flashed disappeared, the second and third cipher try are almost run sequentially within 0.3 seconds.

Just to sum up, the variables:
- play from subscription tab or channel pages, vs play from history tab
- VPN IP address cycling ! swapping different ISP IPs (I have 3 ISP to cycle, because the country's internet provider and media authority sucks)
- UMP video VS iOS videos (no AV1 tested)

Hope this helps from my visual observation of the app's behavior.

This bug is a deal-breaker for me, as I am rarely able to use audio most of the time and need to fall back to subtitles (whether auto-generated or human written).

**Comment by Zvonimir-FUTO** [comment]
@VKen thank you for thorough testing but we can reproduce the issue and are working on a fix. It's just that the fix is not super easy unlike some other bugs.

**Comment by AndrejusAnto** [comment]
> [@VKen](https://github.com/VKen) thank you for thorough testing but we can reproduce the issue and are working on a fix. It's just that the fix is not super easy unlike some other bugs.

Just wondering why because several update before it was working, so how it is that now "is not super easy"?

**Comment by Zvonimir-FUTO** [comment]
POtoken is needed for subtitles now. And they introduced a new change which broke all ad-blocker so we are working on that first.

**Comment by Zvonimir-FUTO** [comment]
Should be finally fixed in the upcoming version.

**Comment by Zvonimir-FUTO** [comment]
New Grayjay and Youtube version released, should be fixed now!

Casting seems to be broken with subtitles, we are looking into that.

**Comment by Rundervinkje** [comment]
Works for me! Thanks for the work!

**Comment by 10mins** [comment]
I still have this issue Youtube version 278 and latest Windows portable version of Grayjay.
In order to get subtitles working I need to change video source once and after that the subtitles works fine.

**Comment by Zvonimir-FUTO** [comment]
@10mins could you please open a separate bug report for this since root cause of the bug for this issue has been fixed and you are probably encountering something else.

https://github.com/futo-org/Grayjay.Desktop/issues/new?template=1-bug_report.yml
