### ISSUE TITLE
Bug: SoundCloud tracks with no "views" don't play

### ISSUE THREAD

**Issue by DrProid** [futo-org/grayjay-android#2338]
### Reproduction steps

![Image](https://github.com/user-attachments/assets/66078cb4-bec4-4375-8976-896656e9846e)

In the attached image, the three songs at the top do not have "views" and do not play.
The three songs at the bottom do have "views" and they play fine.

I'm not sure what removes the "views" and "likes" from the SoundCloud side of things but it seems like checking for null values would be an easy fix.

### Actual result

When trying to play a song without "views" this error appears:

> Failed to load video (ScriptImplementationException) Plugin [SoundCloud]
> 
> [SoundCloud] Expected RatingLikes.likes to be of type V8ValueLong, but found V8ValueNull

### Expected result

Ignore that the video has no "views" or "likes" and play it anyway.

### Grayjay Version

320

### What plugins are you seeing the problem on?

SoundCloud

### Plugin Version

22

### Which android version are you using?

Android 15

### Which device are you using?

Google Pixel 8a

### Which operating system are you using?

Pixel

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

### Are you using a VPN?

No

### Relevant log output

```shell

```

**Comment by stefancruz** [comment]
Fixed on version 23

**Comment by DrProid** [comment]
This bug is back. Same error message. Same reproducibility.

Android version is now 16.
Grayjay Version is now 336.
Plugin version is now 25.

Should this be a new ticket or can we reopen this?

**Comment by stefancruz** [comment]
It's been fixed on version 26.
Thanks for reporting.

**Comment by DrProid** [comment]
Seems to be fixed in SoundCloud plugin version 26.
