### ISSUE TITLE
Bug: Grayjay Android age verify/login fallback broken.

### ISSUE THREAD

**Issue by timmyp53** [futo-org/grayjay-android#2404]
### Reproduction steps

0. Play a youtube age verify/locked content.
1. Attempt to select account with visual ui bug. 
2. Looped age verify dialog box pops up and restarts loop.
3. See video provided below.

### Actual result

Android age verify/login fallback broken. and won't allow you to select an account to watch age locked content.

### Expected result

Select account.

### Grayjay Version

327

### What plugins are you seeing the problem on?

Youtube

### Which android version are you using?

Android 15

### Which device are you using?

Galaxy S24

### Which operating system are you using?

Android 15

### When do you experience the issue?

- [x] While logged in
- [x] While logged out
- [ ] N/A

### Are you using a VPN?

No

### Relevant log output

```shell

```

**Comment by Zvonimir-FUTO** [comment]
Hi Timmy, could you please provide a video recording or something? From my testing, account selection works and I'm unable to reproduce the issue.

**Comment by timmyp53** [comment]
https://gofile.io/d/hGeYD6

Here's a video. Not sure if the account select screen is just not showing properly or what and that is the issue potentially? Not being able to click my account properly.  I already changed system settings on android OS to smallest zoom.

> Hi Timmy, could you please provide a video recording or something? From my testing, account selection works and I'm unable to reproduce the issue.

**Comment by timmyp53** [comment]
Isn't an option to zoom out or scroll or anything. This is new bug as far as I know.

**Comment by Zvonimir-FUTO** [comment]
That UI bug is just how Youtube displays that web page and is a known issue. However it doesn't seem to log you properly in.

Could you try logging in by going to Youtube plugin settings and login from there? Just as a workaround while we figure this out.

**Comment by Zvonimir-FUTO** [comment]
Reproduction steps:

0. Be logged out of Youtube and enable "Allow Age Restricted"
1. Play https://www.youtube.com/watch?v=dSwDa4wKoKc
2. Try to login
3. After you login the same popup shows up instead of logging you in

**Comment by timmyp53** [comment]
I'm able to login after logging out but the age verified videos still have the same issue.

The logging in inside the plugin is bugged and pushes you back a screen like the video but you actually do get logged in.

**Comment by timmyp53** [comment]
Not sure i could capture a video this time due it having P.I.I. during login process but let me know if I can help with something else.

**Comment by timmyp53** [comment]
I also tried tapping or holding on every part of the account profile image to see if I could bypass the ui issue and trick the proper click but it just is responding to too big of a region or something with the taps.

**Comment by timmyp53** [comment]
Updated main post and reproducible steps to be less sarcastic. Sorry about the initial snarkiness. I appreciate you guys.

**Comment by TonioBanderas** [comment]
I have a similar issue.
When I try to log in, in any way btw. it let`s me log in but it does not remeber.
I end up in this UI bugged Browser kind of thing in which I am logged in. But when I close the browser window it tells me that Logging in has failed.
I have had this issue for a while now.

**Comment by timmyp53** [comment]
Yeah its possible I'm not actually logged in but the plugin settings say I am. Not sure. Maybe thats the real issue. We just aren't really logging in?

**Comment by shyshycat** [comment]
So can you guys watch age restricted content or not?

**Comment by timmyp53** [comment]
No I can't. Just have to hope the video isn't tagged as needing age verification.

**Comment by timmyp53** [comment]
Logging in doesn't work for age verification.

**Comment by timmyp53** [comment]
I confirm this also does not work on the grayjay desktop app. Logging in for age verification brings up the weird browser and selecting account does nothing.

Example Video:
https://www.youtube.com/watch?v=ofUi9DR9sc4

**Comment by CoolPenguin42** [comment]
I get the same issue. Cannot get any age restricted video to work. Works with my account on YouTube proper, but on greyjay with that same account logged in, nothing. I get stuck in the same loop too. Age ver -> login -> click my profile -> repeat. Can't break the loop without getting denied. Also seems to maybe happen on account link, since it also loops, but breaking loop on initial account link seems to make it work, since I can see my account playlists, etc when importing..so for some reason that works and age verification does not.

**Comment by timmyp53** [comment]
Yep exactly as I would describe it.

**Comment by Zvonimir-FUTO** [comment]
Should be fixed in the latest version.

**Comment by shyshycat** [comment]
I still get as the other describe the loop login to verify age I'm login in and get back to the page still was never able to watch a age restricted video with grayjay :(

Edit it's an amazing app just wished I finally could be smarter and get to know why I can't watch any of the age restricted videos?

@timmyp53 does it work for you?

**Comment by Zvonimir-FUTO** [comment]
@shyshycat which version of Grayjay and Youtube? Pretty sure we fixed it unless you are encountering some edge case. Also logging in through plugin settings should work as a workaround.

**Comment by shyshycat** [comment]
Version of grayjay 336

YouTube plugin 278

**Comment by Zvonimir-FUTO** [comment]
@shyshycat could you try to reinstall Youtube plugin by going into **Sources** > **Youtube** and at the bottom you should see **Reinstall** button.
Also make sure to update the plugin afterwards.

Please also make sure **Allow Loginfallback** is enabled inside Youtube plugin settings.

**Comment by shyshycat** [comment]
Did the steps you asked me to do.

![Image](https://github.com/user-attachments/assets/d50a0fe5-38ea-42ae-bfe0-e95290a9bcf6)
![Image](https://github.com/user-attachments/assets/67275496-271a-4710-99a4-ceef396d11ee)
![Image](https://github.com/user-attachments/assets/73668cf0-9688-45cf-ba13-30f86758031c)

Still getting this is my account just bugged or what am I doing wrong?

**Comment by Zvonimir-FUTO** [comment]
This is unrelated to the original issue. Looks more like this: https://github.com/futo-org/grayjay-android/issues/1334#issuecomment-3115351785
Could you comment inside that threat if you are using VPN or not?
