### ISSUE TITLE
Bug: Casting loops playback

### ISSUE THREAD

**Issue by rubsl** [futo-org/grayjay-android#2427]
### Reproduction steps

If I'm watching a YouTube video on the phone and I then cast it to a Chromecast Ultra midway through directly from the video page, it connects but won't start playback. To make it work I have to initiate the cast from the front page of the app, before I choose a video to watch. But unless I do it with a completely freshly started app, it casts for a couple of minutes, and then loops back to the same starting point over and over. 
I have to completely shut down the app, restart it, initiate the cast from the front page, find the video again start playback and fast forward to the where I was before, which it doesn't remember on its own. Then it will cast the whole video.
Google pixel 8 Pro, stock Android 15.

1. Start the app
2. Start a YouTube video on the app
3. From the video page, start casting to a Chromecast during playback

### Actual result

Casting connects and initiates in the TV, but doesn't start playback

If it starts, when initiating the casting from the app front page, it loops the playback in a few minutes long loops.

### Expected result

Presumably it is supposed to start the cast and continue the video from the timestamp when I pressed the cast button, and continue the video until it is finished. Just like with the original YouTube app.

### Grayjay Version

327

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

258

### Which android version are you using?

Android 15

### Which device are you using?

Google pixes 8 pro

### Which operating system are you using?

Stock Android 15

### When do you experience the issue?

- [ ] While logged in
- [x] While logged out
- [ ] N/A

### Are you using a VPN?

No

### Relevant log output

```shell

```

**Comment by koen-futo** [comment]
Would you be willing to install the `FCast Receiver` app and give it a shot? That would help us determine if it is networking related or if something else is going on.

https://play.google.com/store/apps/details?id=com.futo.fcast.receiver.playstore&hl=en

**Comment by xephos1one** [comment]
Please check if this got fixed by now with version 363 as there was a bigger change in casting in the meantime
I don't have any playback or looping issues anymore

**Comment by Zvonimir-FUTO** [comment]
Will close this for now since OC didn't reply in a while.

**Comment by rubsl** [comment]
> Please check if this got fixed by now with version 363 as there was a bigger change in casting in the meantime I don't have any playback or looping issues anymore

As far as I experience now, the issue is gone in version 363. Thanks for that! I don't use FCast because my TV is too old.
As of right now, two issues remain when using my Chromecast Ultra.
1. When watching, usually a longer video, like over 20 mins long, the playback randomly pauses, and I have to press play in the app to resume. This happens maybe one every 10 - 15 mins on average.
2. Sometimes when double tapping the video to fast forward or fast reverse, the video just starts over from the beginning, instead of skipping the 10 or 20 seconds that I want it to. His happens in around 1 of 3 videos. In some videos tapping works as intended, in some it restarts the video. There is no obvious pattern.

Thanks for listening to my input! 😁 I like the app more and more.

**Comment by Zvonimir-FUTO** [comment]
@rubsl Thank you for the feedback. Could you please open separate bug reports for these issues? One bug per issue.
