### ISSUE TITLE
Subscriber tile heights not consistent

### ISSUE THREAD

**Issue by stevenkampen** [futo-org/grayjay-android#29]
![Screenshot_20231020-182942](https://github.com/futo-org/grayjay-android/assets/898763/e4c076c1-56e1-4947-bef5-08a0aa3f1b50)

**Comment by defiling9046** [comment]
@Zvonimir-FUTO I believe this is fixed unless this is in a different part of the app.

When i search for "rossmann" the layout is now one creator on top of another.

<img width="1080" height="2424" alt="Image" src="https://github.com/user-attachments/assets/420eb10c-8203-4cf9-bab4-9cb4ff2bd18a" />

**Comment by Zvonimir-FUTO** [comment]
Still needs to be fixed, when using bigger screen or in landscape this bug could still occur.

**Comment by defiling9046** [comment]
> Still needs to be fixed, when using bigger screen or in landscape this bug could still occur.

Oh, makes sense thx
