### ISSUE TITLE
Odysee Playlist  tab fails to load

### ISSUE THREAD

**Issue by ThunderHen** [futo-org/grayjay-android#2966]
Reproduction steps
Open video
Click on channel
Click playlist
Playlist tab doesn't load. 

Actual result
Playlist fails to load 
![](https://i.imgur.com/QXwFmK8.png)

Expected result
Should see playlists for channel 

Grayjay Version

355

What plugins are you seeing the problem on?

Odysee

Plugin Version
59

Which android version are you using?

Android 12

Which device are you using?

Samsung A12

Which operating system are you using?

Android

When do you experience the issue?

While logged out

Are you using a VPN?

Yes

References

Channel where the playlist tab doesn't load 

https://odysee.com/@Lilllyu:29/MakeWayMachinarium:e

**Comment by guerrieronero** [comment]
Same problem still with YouTube plugin, opened a bug report but It was deleted as "duplicate", I don't see it mentioned elsewhere...any update on this?

**Comment by ThunderHen** [comment]
@guerrieronero look like your issue is a duplicate of https://github.com/futo-org/grayjay-android/issues/1979 for YouTube Playlists from doing a search on this repo. 1979 is open unless there is another duplicate issue somewhere else. It's title could be labeled better with a summary of the issues it  outlined. It also looks like it was talking about a outdated version of the plugin and is a older post. Do you have a example playlist for YouTube that don't load for the devs?

**Comment by guerrieronero** [comment]
Umderstood, thanks, hope someone look into It soon. I cannot even get to the selection of playlist it doesn't work/load them so I cannot show a specific playlist as example.
Quick side question: I actually want to support the project and buy the app, I swear I cannot find where to pay for It...directions?

**Comment by ThunderHen** [comment]
I typically either share a link to the video for a channel that I'm trying to give an example for and list out instructions on how to get to the specific issue I'm having or I open the video in the browser and then navigate to the channel playlist or whatever is not working and share the link from the browser.

 I keep forgetting to open an issue for adding an option to share channel links from Grayjay.

 As for payments there is a option to pay in the Grayjay app. That's what I did for Grayjay.

or you can go to https://pay.futo.org/api/PaymentPortal I use the website for futo  keyboard but it also works for GreyJay and Immich.

**Comment by guerrieronero** [comment]
I posted step by step now I get the error (same as the one you posted) in the deleted bug report so I guess It would be redundant reposting once more.
Payment done, thanks... waiting for the issue to be solved, thought was YouTube messing around as they do on a daily basis but seems it's not just that since Odysee Is affected too.

**Comment by Zvonimir-FUTO** [comment]
These are unrelated issues but we will look into both. Thank you for purchasing the license!

**Comment by stefancruz** [comment]
Fixed in version 60.
Thank you for reporting.

**Comment by guerrieronero** [comment]
YouTube issue still going After the last update, at least for me, FYI...

**Comment by Zvonimir-FUTO** [comment]
> YouTube issue still going After the last update, at least for me, FYI...

This is unrelated to Youtube, this was Odysee release.

**Comment by GuyWhoConquers** [comment]
I'm having thxsam issues as well. Except, all my history and playlist are all deleted

**Comment by Zvonimir-FUTO** [comment]
> I'm having thxsam issues as well. Except, all my history and playlist are all deleted

Please read the reply from https://github.com/futo-org/grayjay-android/issues/2971
