### ISSUE TITLE
Bug: Videos in Queue Are All Skipped Until Final Video

### ISSUE THREAD

**Issue by Mr-Savag3** [futo-org/grayjay-android#2989]
### Reproduction steps

1. Select a YouTube video. 
2. Cast to FastCast.
3. Press pause on the video.
4. Browse on your phone for another video, add to queue. Repeat as wanted. 

### Actual result

Each video is played for only about 1 second before being skipped, until the final video in the queue. 

### Expected result

Queue does not advance until current video plays until the end or is skipped by the user.

### Grayjay Version

363

### What plugins are you seeing the problem on?

YouTube

### Plugin Version

311

### Which android version are you using?

Android 16

### Which device are you using?

Google Pixel 7 Pro

### Which operating system are you using?

OEM Android 16

### When do you experience the issue?

- [x] While logged in
- [ ] While logged out
- [ ] N/A

### Are you using a VPN?

No

### Relevant log output

```shell

```

**Comment by VoxelPrismatic** [comment]
Can reproduce.

Logs: [21_12-17-41-19_739.zip](https://github.com/user-attachments/files/24281976/21_12-17-41-19_739.zip)

Video: https://github.com/user-attachments/assets/9140432f-0db2-4258-a55c-0c2bf4de0e40

**Comment by b-risk** [comment]
I can also reproduce, happens with any media local or downloaded, the first video will play and then it will skip through them all

**Comment by Zvonimir-FUTO** [comment]
Should be fixed with latest version of fcast reciever. Could you guys please test and report back?

**Comment by Mr-Savag3** [comment]
I am still experiencing this issue. No idea if the app has updated or not, but it says I don't have any updates available for any apps. 
Chromecast with Google TV, FCast version 2.1.3-playstore
If I need to find a way to install the non-Play Store version, let me know.

Edit: 
I got the non-playstore version and it seems to be working now with no issues.

**Comment by Zvonimir-FUTO** [comment]
Found the new cause, we are working on a fix. Thank you for the feedback.

**Comment by Mr-Savag3** [comment]
> Found the new cause, we are working on a fix. Thank you for the feedback.

It's now happening again.

**Comment by Zvonimir-FUTO** [comment]
Fixed in v14. Make sure to update your FCast receiver as well.
