### ISSUE TITLE
FCasting - Electron, not released

### ISSUE THREAD

**Issue by mnbvasd** [futo-org/grayjay-android#466]
The New Electron version of the FCast app doesn't appear to have been released, following the download link pointed to from https://fcast.org/ -> https://gitlab.futo.org/videostreaming/fcast/-/releases

GrayJay v208

**Comment by koen-futo** [comment]
It was deployed, but I do see there are some issues. Going to solve them now.

**Comment by koen-futo** [comment]
This should be fixed.

**Comment by mnbvasd** [comment]
The Gitlab release page as linked from the main fcast.org site is still showing the 5 month old release tagged "1".

**Comment by koen-futo** [comment]
Correct, but the links are to the build server

**Comment by koen-futo** [comment]
If you are still experiencing issues, are you using the play store version ?

**Comment by mnbvasd** [comment]
Thanks, I just verified it. The release page is a bit misleading in the current form.

I'm just running the Electron versions on Mac and Linux ARM64 so no playstore involved, but a manual build required for Linux.
Its working fine for me, thanks for your help!
