### ISSUE TITLE
Cannot import playlists from youtube

### ISSUE THREAD

**Issue by Alvaro-sD** [futo-org/grayjay-android#85]
When I click on import playlists on youtube from my youtube account none of them appear.

Edit: I'm using the downloaded .apk not the play store install

**Comment by SeppNel** [comment]
Same thing happens to me

**Comment by Luke-L** [comment]
I have the same problem. I wish the Watch Later playlist would auto import, considering one already exists on grayjay

**Comment by cuzimhappyy** [comment]
same problem here, would load for awhile then hang or crash.

**Comment by koen-futo** [comment]
The playlist import for each playlist you have will need to request all the pages of the playlist. If you have many long playlists what could happen is before it finished going through all pages, it hits a rate limit and likely due to lack of proper handling of this case, it crashes.

**Comment by koen-futo** [comment]
Could you give me more information about which playlists you have on your account? mainly the amount of videos in them.

**Comment by cuzimhappyy** [comment]
i have ~20 playlists most are <15 videos long but i have 3 that are longer (45,80,120 videos)

**Comment by SeppNel** [comment]
I have 3 big ones of 116, 171 and 88 + Some smallers ones with < 20 videos.
Don't know if "saved" playists yhay I didn`t create count, but if they do I have another big one with 565 videos.

**Comment by grisevg** [comment]
I think it's caused by non-English Youtube language. I had my Youtube in russian and had same issue. I switched to English and it works now!

Dupes:
https://github.com/futo-org/grayjay-android/issues/141
https://github.com/futo-org/grayjay-android/issues/42
https://github.com/futo-org/grayjay-android/issues/241

**Comment by cuzimhappyy** [comment]
i do have japanese videos in my playlists

**Comment by koen-futo** [comment]
@grisevg Thank you for figuring that out! That is very helpful.

**Comment by Mubelotix** [comment]
> I think it's caused by non-English Youtube language. I had my Youtube in russian and had same issue. I switched to English and it works now!
> 
> Dupes: #141 #42 #241

Switch the language to english didn't help

**Comment by Luke-L** [comment]
nah, my youtube is in en-us. unless one of the videos in a playlist would break it by being in another language, this doesnt do anything.

**Comment by Ser-Bul** [comment]
> @grisevg Thank you for figuring that out! That is very helpful.

Hi Koen, any news?
There's a bunch of similar "can't import playlists" issues reported by multiple people here on Grayjay's GitHub.
I've personally just uploaded verbose logs using the Grayjay app today.

**Comment by Ser-Bul** [comment]
Pinged Koen in [chat.futo.org](https://chat.futo.org/#narrow/stream/46-Grayjay/topic/YT.20playlists.20import.20doesn't.20work) as well. Hope we'll get some reply soon.

**Comment by Werner1201** [comment]
Same here, @Ser-Bul, changed the language, didn't work. As I said in that chat: "I even looked into the .js URL script, and It seems the const URL_PLAYLIST and URL_PLAYLISTS_M are not assigned correctly, Youtube "recently" changed the URL_PLAYLIST_M (Which I assume the M is for menu) and the menu link changed to: [which ever youtube base url]/feed/playlists.
That's what I think it's the problem"
I studied programming and JS programming for a while, but I might be completly and utterly wrong about this issue. I just don't have the time to enter dev mode download youtube plugin source code and test it on my device
If anyone has the knowledge to do it, give it a try the tutorial seems fairly easy.

**Comment by Werner1201** [comment]
![image](https://github.com/futo-org/grayjay-android/assets/8631657/75c94761-61d4-47cc-8b7c-8cfed28f2745)
The URL on the URL_PLAYLISTS_M directs to the image shown above. 
[The gitlab code I'm refering to](https://gitlab.futo.org/videostreaming/plugins/youtube/-/blob/master/YoutubeScript.js?ref_type=heads) on the line 21 the const I'm refering to. 

The correct playlist menu I see when I click playlist on youtube is this:
![image](https://github.com/futo-org/grayjay-android/assets/8631657/68326ff0-314a-4d68-b597-991d0a4e124e)
`https://www.youtube.com/feed/playlists`

**Comment by Ser-Bul** [comment]
"Good news everyone": one of the developers replied in [chat.futo.org](https://chat.futo.org/#narrow/stream/46-Grayjay/topic/YT.20playlists.20import.20doesn't.20work). The YT plugin update should be published next week, bringing some fixes for the playlists import.

**Comment by Ser-Bul** [comment]
Plugin v.182, the issue is still there. Pinged devs in futo chat.

**Comment by Mubelotix** [comment]
> Plugin v.182, the issue is still there. Pinged devs in futo chat.

I think you should leave them some space. They also have other issues to work on, maybe this isn't the priority right now

**Comment by Ser-Bul** [comment]
I think they are are mature, independent people who make their own decisions and are able to tell us their priorities if necessary.

**Comment by SupremeLobster** [comment]
This is still an issue as of the latest update. It doesnt appear to even attempt to load the playlists.

**Comment by SupremeLobster** [comment]
As of the latest update, it appears the changing the youtube language to English (US) (during the login page), fixes the issue. It seems I can now import large playlists (a few hundred videos) but very big playlists (like thousands of videos) are still an issue.

**Comment by Crckwood** [comment]
> As of the latest update, it appears the changing the youtube language to English (US) (during the login page), fixes the issue. It seems I can now import large playlists (a few hundred videos). Importing very large playlists (thousands of videos) does work but it takes a few minutes.

Switching my account from Canadian French to English US after login in the plug-in DID resolved the issue. Thank you !

**Comment by Ser-Bul** [comment]
> Switching the language to english didn't help

Surprisingly it worked for me now.
Either the latest update fixed the problem or I tried to switch the language in some wrong way before.

The list of actions that fixed the issue for me today:

- [x] In Grayjay app go to Sources > Youtube
- [x] tap "Logout without Clear"
- [x] then tap "Login", Youtube webpage opens
- [x] on the top-right corner of the webpage click on the icon of your profile/account, then pick "Language" and select "English (US)"
- [x] return back (to Grayjay)
- [x] tap "Login" again and this time on the webpage just tap your account in the middle of the screen (not on the top-right corner)
- [x] that brings you back to Grayjay where you can now tap "Import Playlists". That will work.
Though it will show some errors if your playlists have videos hidden (deleted?) by Youtube.

**Comment by SupremeLobster** [comment]
> > Switching the language to english didn't help
> 
> Surprisingly it worked for me now.
> Either the latest update fixed the problem or I tried to switch the language in some wrong way before.
> My case is that I've been getting message 'Nothing to import' in Grayjay as I was trying to import Youtube playlists.
> The list of actions that fixed the issue for me today:
> 
> - [x] In Grayjay app go to Sources > Youtube
> - [x] tap "Logout without Clear"
> - [x] then tap "Login", Youtube webpage opens
> - [x] on the top-right corner of the webpage click on the icon of your profile/account, then pick "Language" and select "English (US)"
> - [x] return back (to Grayjay)
> - [x] tap "Login" again and this time on the webpage just tap your account in the middle of the screen (not on the top-right corner)
> - [x] that brings you back to Grayjay where you can now tap "Import Playlists". That will work.
> Though it will show some errors if your playlists have videos hidden (deleted?) by Youtube. 

Yep it has been fixed in the latest update!

**Comment by Pdzly** [comment]
Sadly i can not import any playlists again. I tried your solutions but nothing worked. It only shows "Liked Videos" and "Watch Later" playlists.

Logged out and in still nothing.

**Comment by SeppNel** [comment]
@Zvonimir-FUTO Still happening to me if the login page is not in english.

**Comment by darkkmage** [comment]
I'm also experiencing the same issue here. My language was already English (US) and my region was already USA. I tried logging out of YouTube in GreyJay, then logging back in, then selecting English (US) and USA within the login window in GreyJay but that didn't help at all.

I have many very large YT playlists. For me, the importer consistently caps out at 46 playlists, then hangs there.

**Comment by eklenin** [comment]
I have same issue, when trying to import YT playlists, I get "Nothing to import".
Initially, I managed successfully import about 50 of them, but since some time this feature stopped working.

Also, "Playlists" section of any channel shows nothing.

I also have a lot of videos in YT "Watch Later" playlist, and many of them often get deleted due to YT censureship, not sure if it's related or not.

**Comment by Zvonimir-FUTO** [comment]
Do affected users have a channel on Youtube? Not only account but channel as well to which you can upload video. No uploads are needed though.

**Comment by SeppNel** [comment]
I actually have 2 channels

**Comment by eklenin** [comment]
> Do affected users have a channel on Youtube? Not only account but channel as well to which you can upload video. No uploads are needed though.

I have a channel, without uploads.
Also I used to have second channel "managed" by the youtube account I logged in on grayjay, but I unlinked it later

**Comment by Zvonimir-FUTO** [comment]
Thanks for feedback guys, now I can kinda reproduce it. With 2 channels, I get only 7 subscriptions.

**Comment by Anderslv** [comment]
For me, the login window is zoomed in and squeezed to a degree where choosing the right account is difficult. When I manage to choose the correct account, I cannot see any playlists. 

I do see my subscriptions though, which I then imported in chunks, for which every second chunk left the visualization hanging at some procentage, having seemingly succesfully imported the selected subscriptions. I then closed down the app, and the pattern repeted itself again and again until I was done.

I did manage to change language settings to English (US) during login, and now my playlists are available for import. Import doea seem to overwhelm the app, though, causing it to hang with no message of completion appearinf for large playlists.

I used the direct download link on the webpage for the installer, and the app is on version 330. I am using a Samsung S22 Plus with Android 15 & One UI 7.0.

**Comment by Zvonimir-FUTO** [comment]
Think this was fixed in previous release. Can you guys still reproduce this?

**Comment by SeppNel** [comment]
@Zvonimir-FUTO Still happening to me.
Language set to Spanish while choosing profile = No playlists to import
Language set to English = Playlists show up.

I can record a video if needed

**Comment by Zvonimir-FUTO** [comment]
Please do :)

**Comment by SeppNel** [comment]
[recording_20251104_163020.zip](https://github.com/user-attachments/files/23340192/recording_20251104_163020.zip)

**Comment by Zvonimir-FUTO** [comment]
Finally fixed in v309! Thank you all for reporting, especially to @SeppNel who figured it out :)

**Comment by guerrieronero** [comment]
I have version 309 and problem persists, "Cannot read properties of 'null' (reading 'contents') (3325)[28-29]" on Lenovo tablet M10 3rd gen - android 12.

**Comment by Zvonimir-FUTO** [comment]
@guerrieronero Can you post a screenshot?

**Comment by guerrieronero** [comment]
Sure.

![Image](https://github.com/user-attachments/assets/9bc592a0-5870-4e93-8563-1de4b32afdc6)

**Comment by Zvonimir-FUTO** [comment]
Unfortunately we weren't able to reproduce this. The error message is basically saying that you get served different UI then expected. This is hard to fix without being able to reproduce it first.

**Comment by guerrieronero** [comment]
So the day After I bought the app, the app became basically useless for what I needed it most. Classic FML moment. 😂

**Comment by Zvonimir-FUTO** [comment]
Does logging out and back in helps? 
Can you try changing the language of Youtube website in webview to english and see if helps?

**Comment by guerrieronero** [comment]
Well well well, the old "turn it off then on again" always work...should have known. I restarted app and tablet several times but did not in fact disconnect and relogged in, thought it was automatic process - and several times doing the Gmail login in apps and such get stubbornly stuck so I tend to avoid It if possibile.
Anyways, It works now, slightly my fault this last part but if someone else Is stuck there maybe It helps.
Thanks for the assistance.

**Comment by Zvonimir-FUTO** [comment]
Thank you for the feedback!

**Comment by JacobPlaysGames** [comment]
I am unable to import playlists. I have logged out and back in multiple times.

This has been ongoing for a few months now so it isn't just a temporary issue.

![Screenshot_20260212-192906.png](https://github.com/user-attachments/assets/82387a90-28b0-4f80-b86a-cf6766fd6784)

**Comment by nbhirud** [comment]
![Screenshot_20260613_013043_Grayjay.jpg](https://github.com/user-attachments/assets/6ecc13f2-7dcf-434f-a610-dde854f9615c)
Don't know if this is related. But I'm getting this error when I try to play any playlist from search results.

**Comment by Zvonimir-FUTO** [comment]
@nbhirud please check https://github.com/futo-org/grayjay-android/issues/3343
